"""Add saved_password

Revision ID: 451e93b502d7
Revises: bcfaf14d817f
Create Date: 2026-02-28 15:09:53.045329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451e93b502d7'
down_revision: Union[str, Sequence[str], None] = 'bcfaf14d817f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('saved_password', sa.String(), nullable=True))
    op.alter_column('devices', 'has_agent',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'has_agent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('devices', 'saved_password')
    # ### end Alembic commands ###
