"""rename_groupement_to_devision

Revision ID: f40edbb5d8ee
Revises: 451e93b502d7
Create Date: 2026-03-01 16:38:19.312454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40edbb5d8ee'
down_revision: Union[str, Sequence[str], None] = '451e93b502d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Rename groupements to devisions
    # Since services already references devisions, this will fix the FK relation
    op.rename_table('groupements', 'devisions')
    
    # Add info column to devisions
    op.add_column('devisions', sa.Column('info', sa.String(), nullable=True))
    
    # Indices are already part of the rename in some alembic/sqlite versions, 
    # but let's be safe. Actually, op.rename_table usually renames indices too.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'groupements', ['groupement_id'], ['id'])
    op.alter_column('devices', 'has_agent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('groupements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupements_name'), 'groupements', ['name'], unique=1)
    op.create_index(op.f('ix_groupements_id'), 'groupements', ['id'], unique=False)
    # ### end Alembic commands ###
